spring:
  main:
    banner-mode: "off"
  jersey:
    type: filter

logging.level:
  org.dotwebstack.framework: DEBUG

dotwebstack:
  config:
    resourcePath: file:/opt/config
    systemGraph: http://dotwebstack.org/configuration/Theatre
